//
// Created by potteplante on 6/23/22.
//

#ifndef COMMONDATASTRUCTURESPRACTICE_STICKYSTACK_H
#define COMMONDATASTRUCTURESPRACTICE_STICKYSTACK_H

#endif //COMMONDATASTRUCTURESPRACTICE_STICKYSTACK_H
